### ISSUE TITLE
Need modification in "Makefile" and "miopen.hpp"

### ISSUE THREAD

**Issue by pramenku** [patflick/miopen-benchmark#6]
As per latest release 1.6.4 of rocm driver , library name of rocblas and hipblas needs to be changed from ""-lhipblas-hcc , -lrocblas-hcc"  to ""-lhipblas -lrocblas" 
Hence, Makefile needs modification as below 
LD_FLAGS=-L$(ROCM_PATH)/lib -L$(ROCM_PATH)/opencl/lib/x86_64 -lMIOpen -lOpenCL -lmiopengemm -lhipblas -lrocblas

Besides this, 1 minor modification requires in miopen.hpp as below
#include <hipblas/hipblas.h> to #include <hipblas.h>

Only after above 2 modification, we can able to build the miopen-benchmark tests on rocm release 1.6.4

**Comment by patflick** [comment]
can you send this as a pull request?

**Comment by pramenku** [comment]
I havae created pull request for below:
Besides this, 1 minor modification requires in miopen.hpp as below
#include <hipblas/hipblas.h> to #include <hipblas.h>

But , somehow pull request was not coming for Makefile changes and it went directly, not sure why.

**Comment by pramenku** [comment]
Can you please merge the changes asap.

**Comment by patflick** [comment]
Done.

**Comment by pramenku** [comment]
Thanks.
